// frontend/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'frontend10';
}

<mat-tab-group mat-align-tabs="start">
  <mat-tab>
    <ng-template mat-tab-label>
      <a routerLink="/project-view"><i class="el-icon-ship"></i> 项目视图</a>
    </ng-template>
  </mat-tab>
  <mat-tab>
    <ng-template mat-tab-label>
      <a routerLink="/date-view"><i class="el-icon-ship"></i> 日历视图</a>
    </ng-template>
  </mat-tab>
  <mat-tab>
    <ng-template mat-tab-label>
      <a routerLink="/history-view"><i class="el-icon-ship"></i> 历史视图</a>
    </ng-template>
  </mat-tab>
</mat-tab-group>
<router-outlet></router-outlet>

// frontend/src/main/typescript/App.vue
<template>
    <div>
        <el-tabs type="border-card">
            <el-tab-pane>
                <span slot="label"><i class="el-icon-ship"></i> 项目视图</span>
                项目视图
            </el-tab-pane>
            <el-tab-pane>
                <span slot="label"><i class="el-icon-date"></i> 日历视图</span>
                日历视图
            </el-tab-pane>
            <el-tab-pane>
                <span slot="label"><i class="el-icon-coin"></i> 历史视图</span>
                历史视图
            </el-tab-pane>
            <el-tab-pane>
                <span slot="label"><i class="el-icon-baseball"></i> Demo视图</span>
                <demo></demo>
            </el-tab-pane>
        </el-tabs>
    </div>
</template>
<script lang="ts">
export { default } from "./App";
</script>
<style lang="scss" module>
</style>
